#!/usr/bin/env python
""" GUI admin permission """
# -*- coding: utf-8 -*-
#
# Copyright 2015 Fotios Tsiadimos
# Licensed under the terms of the GPL License
# (see License file for details)

import subprocess
subprocess.call(['pkexec', '/usr/lib/python2.7/site-packages/netspy2ban/netspy2ban'])
